{% set name = "fortio" %}
{% set version = "0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fortio-{{ version }}.tar.gz
  sha256: e143fbb8cc2644550b3b08ecef62eae190daf82377b5527a68d04037be934650

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - numpy
    - python >={{ python_min }}

test:
  imports:
    - fortio
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/syrte/fortio/
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE
  summary: 'A Python IO for Fortran Unformatted Binary File with Variable-Length Records.'
  description: |
    A Python IO for Fortran Unformatted Binary File with Variable-Length 
    Records.
  doc_url: https://github.com/syrte/fortio/
  dev_url: https://github.com/syrte/fortio/

extra:
  recipe-maintainers:
    - jan-janssen
